language: c

git:
  depth: 5

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.conan
  - /usr/local/Homebrew

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8-multilib
      - linux-libc-dev
      - g++-4.8
      - texlive
      - texinfo
      - valgrind
  coverity_scan:
    project:
      name: $TRAVIS_REPO_SLUG
      description: MATLAB MAT File I/O Library
    notification_email: $COVERITY_SCAN_EMAIL
    build_command: make
    branch_pattern: coverity_scan

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "C2T0NCiqo98RZXaBTqSWpxcpKhAryOD9VcZ02keuyOPCeNpaLKeo36R/8iAhHWvQddU3V9x0H8EHGN4QY78I1kH3OTwTsGueyRTjKvBsrWlR88pO0CJ33MXz9IvpVE32zACKt2Ltj2GBIUzl0Nm6uwjJXW59pL/86X9ShHK/+hs8Trqu3Zm8MiWg0z79xZzHo+9m7RXW0i5jwxBfIbW15GIMc1TMZC31eHBDjQRCTL89IZzJXVf1ZCd+OsUpvuOVneAl9ihvqyZ3fkK/8n7iVr3TzJDIpj4I3AgVSdg6D0vNsW5HE/czZKTHs6yVI/ImcpPnyApd85MKxjkyppDi3WTBvWn4MkPDMxj1ZJzDQ+0tGIcfaQn9uXiwZCIIezodFK5aY8/OoK9/cVRfjHjZrXkv+hfH0Xys9DrlhSKpeusU0hAS2yoz10g+aN/Sz4fGeRlGrvU0HIncFdXLsD30v7LDTZn4dBIH7C+xE6pbcQ7Y3bGEC3CyR0UbFCbjY20JPMa0k7FBmLRpBUHn9mxJ/eJSnWH/ZI4YRWyJd5fAQvUPvY+5oP+IaEo0oZgSelEUnEssmySFFrVN4YC1GJb63AT7tLPnhgghmzSZUMG/l7Zj0++TEQv+OhtVg8E57iSV0l7WXXwapCyjbFHvjPEwvgZ3plc9XOo+HqYxeHtkx40="
    # COVERITY_SCAN_EMAIL
    - secure: "Qux4CPWkAXdpWPbUwqKTtimTU/xKC2oLtqzH5oMYuTUqyAX9D6XAEx+lq5ADNk5UAQuq4kCWYxPyNOu85vZPV/9INBZ9sSJ+Y5cbQLpJ6nqY7nQHuL5WoIHDtyabgo3mKlsY4mkpM0qcHgHib98/j7vG573pBfp4ihcUu5eKUNxlP07nUILeBPpuJz5GWoCzikU9M0tgjwmydWoa+dJ726HPoPjsu2VY1RFov63u+BWX/c3FUTWyleGVIsQbQeQUcIjMMtHyv0r3wqdsryk88m1rEpDrAy60fki71lcfGuxhzgkSMLezFu2Qj8EqtUrC+Xh4/VIFdn3XbR527OrTQrkJYDelZvEQSoEd3NgiWu5A0R+Zr68YJLjPHoW4TJFj0AG7Nek9bBr27CJOMjAzBVp8FMcVl3/6ApfJb0R89vslPA0J+p/UJdmjhuriiigojMwJQwESpRLtp+oietfr2UtQUeMc9AqCZf4jRzNK4ooEC75Z9MM2FFiuDLhAyYsCwwHrHilXHCCStdjs1jk7YV1+AyU5HIokAYPXjWwxT5BWSIc5wfnIj4lGdMhzJien8/qjyU6kQPiikorKTgd2eD6KzQULuccPudnN9lK6eT+DY4LZ3rfSMGFkMA72w0nmEK4sTGuT8zMC9KS0hgat5b8mzSJ3xhaXig3gQXkrYZk="
    # BBTOKEN
    - secure: "JImOuwX2cdh28rD1WorwdpcUnx1eOTK0DKU8jwMbNlmJsQ/tL0H2ErWqsHmGXR8/cZ/cElAg9BNA5sEkKm34egidvxiXDjYLJWsBrMXVmLo6nZEKcNNJm5dGRvPCJiGNxdeMH4ytn65MJor5oOwyETgQpjnrcZL1M++PAjUZdKR66fizxxD4qmCO8egRgvrCvaR41vHkhX4bwqBI5dfIXIb0M0i1a+ge6rD+LwSx4Bpj3jub4Z/Ik+9epZTsP7iTfzvuDBqkP6P7UU1fyZ6o+CauWJ/EQ+nf31Ofd1kaAwgOrLnu3+K/5kuavC/hZ3WaDurC7f6SbyiRH6zuAgMzJB04+IbHy5OTgPpx1O+qZtVOjXlm2TsIKxil1EzBQGLN8tRpFvSOVE+a89WhiNsO0ZxvDOo1Irt1BnrKGssLDLSqmnhbLuJoVZOPwBUWqgOmP2+9nCsQE2CpoE35efMVuI2Dhe/en0HzhcgJucXaspweGi+0cdLkKAmP5oHMmPxvFmLmjG0YbO0J1AHPZ37mSRl9GDYxKbXUWVXlqSNEffs9fgSsAoHL0xTbGbmPQN0LRixc04UGGXFyUfEsdVOW/Qjxv1kHC3A3doVM9h5d+fHugclF1KYrgtMMiQ9Ssp2ZCEPbo7urs5gqrx+cG294mAXZH8W/hrX7TJ21a/DXiSc="

jobs:
  include:
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.14
        - HDF5_PATCH_VERSION=5
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.12
        - HDF5_PATCH_VERSION=3
        - MAX_RANK=3
    - os: linux
      arch: arm64
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.12
        - HDF5_PATCH_VERSION=3
        - MAX_RANK=3
    - os: linux
      arch: s390x
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.12
        - HDF5_PATCH_VERSION=3
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.10
        - HDF5_PATCH_VERSION=11
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=1
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=no
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=no
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=no
        - WITH_ZLIB=no
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=no
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=no
        - ENABLE_MAT73=yes
        - WITH_ZLIB=no
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=no
        - ENABLE_MAT73=no
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=no
        - ENABLE_MAT73=no
        - WITH_ZLIB=no
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - USE_CMAKE=yes
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.10
        - HDF5_PATCH_VERSION=10
    - os: linux
      compiler: gcc-4.8
      env:
        - PATH=/opt/python/3.7.1/bin:$PATH
        - USE_CMAKE=yes
        - USE_CONAN=yes
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
    - os: linux
      compiler: clang
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3
    - os: osx
      compiler: clang
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3
    - os: osx
      osx_image: xcode13.4
      compiler: clang
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=/usr/local/opt/zlib
        - MAX_RANK=3
        - HDF5_VERSION=foo
        - HDF5_PATCH_VERSION=bar
        - HOMEBREW_DEPLOY=yes
        - HOMEBREW_NO_ANALYTICS=1
    - os: osx
      osx_image: xcode12.5
      compiler: clang
      env:
        - USE_CMAKE=yes
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
    - os: freebsd
      compiler: clang
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=no
        - WITH_ZLIB=no
        - HDF5_VERSION=1.8
        - HDF5_PATCH_VERSION=23
        - MAX_RANK=3

before_install: bash ./.ci/travis_before_install.sh || travis_terminate 1;

install: bash ./.ci/travis_install.sh || travis_terminate 1;

before_script: bash ./.ci/travis_before_script.sh || travis_terminate 1;

script: bash ./.ci/travis_script.sh || travis_terminate 1;

after_success: bash ./.ci/travis_after_success.sh || travis_terminate 1;

notifications:
  email: false
